name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Fetch Dockerfile and script.sh
        run: |
          mkdir -p Docker
          wget -O Docker/Dockerfile https://raw.githubusercontent.com/mouliveera/learnwithUs/refs/heads/main/Docker/Dockerfile

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t mouliveera/learnwithus:${{ inputs.docker_tag }} -f Docker/Dockerfile Docker/
          docker push mouliveera/learnwithus:${{ inputs.docker_tag }}
