name: Reusable Workflow

on:
  workflow_call:
    inputs:
      AppId:
        description: 'PlanIT application ID number, excludes APP- (ex. "4853")'
        required: true
        default: '0'
        type: string
      VpcId:
        description: 'VPC to provision the pipeline'
        required: true
        type: string
      RepositoryName:
        description: 'GitHub Enterprise repository name (ex. "HIG/ds_mlops_core_dags")'
        required: true
        type: string
      BranchName:
        description: 'GitHub Enterprise branch name'
        required: true
        type: string
jobs:
  print-values:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "AppId: ${{ inputs.AppId }}"
          echo "VpcId: ${{ inputs.VpcId }}"
          echo "RepositoryName: ${{ inputs.RepositoryName }}"
          echo "BranchName: ${{ inputs.BranchName }}"
