name: Deploy Release Container

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      AppId:
        description: 'PlanIT application ID number (ex. "4853")'
        required: true
        type: string
      VpcId:
        description: 'VPC to provision the pipeline'
        required: true
        type: string
      RepositoryName:
        description: 'GitHub Enterprise repository name (ex. "HIG/ds_mlops_core_dags")'
        required: true
        type: string
      BranchName:
        description: 'GitHub Enterprise branch name'
        required: true
        type: string
      ReleaseName:
        description: 'Release Name Of Astro Deployment'
        required: true
        type: string
      AirflowVersion:
        description: 'Version tag of Airflow (ex. 2.4.3-2)'
        required: true
        type: string
      TimeoutAndRegion:
        description: 'JSON for TimeoutInMinutes and AWSRegion'
        required: true
        default: '{"AWSRegion":"us-west1","TimeoutInMinutes":10}'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Inputs
        id: parse_inputs
        run: |
          echo "APP_ID=${{ github.event.inputs.AppId }}" >> $GITHUB_ENV
          echo "VPC_ID=${{ github.event.inputs.VpcId }}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${{ github.event.inputs.RepositoryName }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.inputs.BranchName }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${{ github.event.inputs.ReleaseName }}" >> $GITHUB_ENV
          echo "AIRFLOW_VERSION=${{ github.event.inputs.AirflowVersion }}" >> $GITHUB_ENV
          
          echo '${{ github.event.inputs.TimeoutAndRegion }}' > timeout_region.json
          cat timeout_region.json | jq .

          echo "AWS_REGION=$(jq -r '.AWSRegion' timeout_region.json)" >> $GITHUB_ENV
          echo "TIMEOUT_IN_MINUTES=$(jq -r '.TimeoutInMinutes' timeout_region.json)" >> $GITHUB_ENV

      - name: Print Parsed Inputs
        run: |
          echo "AppId: $APP_ID"
          echo "VpcId: $VPC_ID"
          echo "RepositoryName: $REPOSITORY_NAME"
          echo "BranchName: $BRANCH_NAME"
          echo "ReleaseName: $RELEASE_NAME"
          echo "AirflowVersion: $AIRFLOW_VERSION"
          echo "AWSRegion: $AWS_REGION"
          echo "TimeoutInMinutes: $TIMEOUT_IN_MINUTES"
